# Generated by Django 5.2.1 on 2025-05-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hoteluser_options_alter_hotelvendor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvendor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
