# Generated by Django 5.2.1 on 2025-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hotelvendor_is_verified_alter_hotel_hotel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelvendor',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
